a = float(input("Введите значение а: "))
b = float(input("Введите значение b: "))
c = float(input("Введите значение c: "))
x = complex((-b + (b ** 2 - 4 * a * c) ** 0.5 ) / a * 2)
print("Решение задачи:", x)
